### ISSUE TITLE
Upgrade to ZIO 2.0

### ISSUE THREAD

**Issue by swoogles** [zio/zio-akka-cluster#145]
ZIO is at Milestone 4, with an RC expected in the next few weeks.
https://github.com/zio/zio/releases/tag/v2.The API is nearly stable at this point, so any early migration work against this version should pay off towards the official 2.0 release.

The progress is being tracked here:
zio/zio#5470

The Stream Encoding work in progress is the only area where the API might still change before the RC.

To assist with the migration, follow this guide:
https://zio.dev/howto/migrate/zio-2.x-migration-guide/

We are actively working on a ScalaFix rule that will cover the bulk of the simple API changes:
https://github.com/zio/zio/blob/series/2.x/scalafix/rules/src/main/scala/fix/Zio2Upgrade.scala

If you would like assistance with the migration from myself or other ZIO contributors, please let us know!

**Comment by justcoon** [comment]
working on migration

**Comment by swoogles** [comment]
@ghostdogpr Should we create a side branch for ZIO2 until we are past the RCs?
@justcoon has completed the work for RC1

**Comment by ghostdogpr** [comment]
> @ghostdogpr Should we create a side branch for ZIO2 until we are past the RCs? @justcoon has completed the work for RC1

Yep, I just created the `series/2.x` branch.

**Comment by ghostdogpr** [comment]
Snapshot published for 2.0.0-RC1: https://oss.sonatype.org/content/repositories/snapshots/dev/zio/zio-akka-cluster_2.13/0.2.0+40-5cb8e57d-SNAPSHOT/

**Comment by swoogles** [comment]
Awesome, thanks!
